### ISSUE TITLE
Not localized WARN signal leaks to other modules

### ISSUE THREAD

**Issue by jsf116** [stevieb9/file-edit-portable#38]
In line 6 the WARN signal is made error:
`$SIG{__WARN__} = sub { confess(shift); };`

This leads to unexpected and quite disturbing side effects if this signal should not be handled in this manner after the module File::Edit::Portable or any other module using it is used.

A localization of this signal inside your module would be greatly appreciated!

**Comment by sushrutp** [comment]
++

**Comment by stevieb9** [comment]
This is fixed in v1.26.
